apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.1.1.249  # whiteserver
    ports:
      - port: 1
  - addresses:
      - ip: 10.1.1.250  # blackserver
    ports:
      - port: 1
  - addresses:
      - ip: 10.1.1.64   # asusserver
    ports:
      - port: 1
---
api pessoVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
