apiVersion: v1
kind: Service
metadata:
  name: nextcloud-aio-service
spec:
  selector:
    app: nextcloud-aio
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP  # Use LoadBalancer or Ingress for external access
